"""0005-help-and-docs: help, the generated reference, the guide's build, the agent skill, fresh."""
import hashlib
import json
import os
import re
import shutil
import stat
from pathlib import Path

from ws_host.commands import docs
from ws_host.core import registry as reg
from .helpers import REPO, Home

TOPICS = {"start", "repos", "signin", "trust", "kits", "editor", "shell", "recover", "ai", "extend"}


class Help(Home):
    def test_help_lists_the_topics_the_spec_requires(self):
        code, doc = self.run_json("help")
        self.assertEqual(code, 0)
        self.assertTrue(TOPICS <= {t["name"] for t in doc["data"]["topics"]})
        self.assertEqual(doc["data"]["count"], len(doc["data"]["topics"]))

    def test_a_topic_is_a_resource_with_plain_first_line_sections_and_steps_as_actions(self):
        for name in sorted(TOPICS):
            code, doc = self.run_json("help", name)
            self.assertEqual(code, 0, name)
            self.assertEqual(doc["kind"], "help")
            self.assertTrue(doc["data"]["plain"].endswith("."), name)
            self.assertTrue(doc["data"]["sections"], name)
            self.assertTrue(doc["actions"], name)
            for a in doc["actions"]:
                self.assertIn(a["command"].split()[0], {c.words[0] for c in reg.discover().commands.values()})
                self.assertTrue(a["cli"] is None or a["cli"].startswith("ws-host "))
            _, text = self.run_cmd("help", name)
            self.assertEqual(text.splitlines()[0], doc["data"]["plain"])
            self.assertNotRegex(text.splitlines()[0], r"\b(json|stderr|uv\.lock|fast-forward|symlink)\b")

    def test_an_unknown_topic_lists_the_real_ones(self):
        code, doc = self.run_json("help", "nonesuch")
        self.assertEqual((code, doc["data"]["code"]), (2, "usage"))
        self.assertIn("repos", doc["data"]["message"])

    def test_topics_work_offline_with_nothing_installed(self):
        os.environ["WS_HOST_OFFLINE"] = "1"
        code, _ = self.run_cmd("help", "start", "--offline")
        self.assertEqual(code, 0)

    def test_the_check_section_passes_and_fails_for_a_topic_naming_a_command_that_is_gone(self):
        self.assertEqual(self.run_json("check", "help")[0], 0)
        r = reg.discover()
        from ws_host.core.registry import Step
        t = r.topics["start"]
        saved = t.steps
        t.steps = saved + (Step("Bad", ("nonesuch", "verb")), Step("Worse", ("repo", "list"), {"bogus": 1}))
        try:
            code, doc = self.run_json("check", "help")
        finally:
            t.steps = saved
        self.assertEqual(code, 1)
        msgs = " ".join(f["message"] for f in doc["data"]["sections"][0]["findings"])
        self.assertIn("does not exist", msgs)
        self.assertIn("bogus", msgs)

    def test_topics_mention_nothing_this_ws_host_does_not_have(self):
        for t in reg.discover().topics.values():
            text = t.plain + " ".join(h + x for h, x in t.sections)
            for word in ("persona", "devcontainer", "Codespaces", "Nix", "YAML"):
                self.assertNotIn(word, text, t.name)

    def test_the_shell_topic_says_bash_and_oh_my_posh_are_supported_and_fish_4_is_best(self):
        text = " ".join(h + " " + x for h, x in reg.discover().topics["shell"].sections) + reg.discover().topics["shell"].plain
        for needle in ("bash", "oh-my-posh", "fish 4", "chsh", "never changes your login shell"):
            self.assertIn(needle, text)

    def test_the_extend_topic_describes_only_the_python_registry_way(self):
        t = reg.discover().topics["extend"]
        text = " ".join(x for _, x in t.sections)
        for needle in ("Python", "ws_host/commands", "ws_host/kits", "pyproject.toml", "uv.lock", "standard library", "doctor", "fresh"):
            self.assertIn(needle, text)
        for forbidden in ("YAML", "requirements.txt", "pip install", "Nix"):
            self.assertNotIn(forbidden, text)


class Generated(Home):
    def test_the_committed_reference_and_skill_are_current(self):
        code, doc = self.run_json("fresh")
        self.assertEqual(code, 0, doc["data"])
        self.assertEqual({g["name"] for g in doc["data"]["generators"]}, {"agent-skill", "reference-docs"})

    def test_every_generated_file_carries_a_header_naming_its_generator_and_command(self):
        for rel, text in reg.discover().generators["reference-docs"].render().items():
            self.assertIn("Generated by ws-host: reference-docs", text.splitlines()[0], rel)
            self.assertIn("ws-host docs generate", text.splitlines()[0])
        skill = reg.discover().generators["agent-skill"].render()[".claude/skills/ws-host/SKILL.md"]
        self.assertTrue(skill.startswith("---\nname: ws-host\n"))
        self.assertIn("ws-host skill generate", skill)

    def test_a_hand_edit_makes_fresh_fail_naming_the_generator_and_the_command(self):
        f = REPO / "docs-src" / "chapters" / "reference" / "commands.adoc"
        original = f.read_text()
        try:
            f.write_text(original + "\nedited by hand\n")
            code, doc = self.run_json("fresh")
            self.assertEqual(code, 1)
            self.assertEqual(doc["actions"][0]["cli"], "ws-host docs generate")
            self.assertIn("reference-docs", json.dumps(doc["data"]))
            code, doc = self.run_json("check", "fresh")
            self.assertEqual(code, 1)
            self.assertIn("docs generate", doc["data"]["sections"][0]["findings"][0]["message"])
        finally:
            f.write_text(original)
        self.assertEqual(self.run_json("fresh")[0], 0)

    def test_a_missing_generated_file_is_stale(self):
        f = REPO / "docs-src" / "chapters" / "reference" / "kits.adoc"
        original = f.read_text()
        f.unlink()
        try:
            self.assertEqual(self.run_json("fresh")[0], 1)
        finally:
            f.write_text(original)

    def test_generate_dry_run_writes_nothing_and_a_real_run_is_idempotent(self):
        code, doc = self.run_json("docs", "generate", "--dry-run")
        self.assertEqual(code, 0)
        self.assertTrue(all(f["status"] == "unchanged" for f in doc["data"]["files"]))
        code, doc = self.run_json("docs", "generate")
        self.assertTrue(all(f["status"] == "unchanged" for f in doc["data"]["files"]))
        code, doc = self.run_json("skill", "generate")
        self.assertEqual(code, 0)

    def test_the_reference_lists_every_command_kit_topic_and_config_key(self):
        out = reg.discover().generators["reference-docs"].render()
        commands = out["docs-src/chapters/reference/commands.adoc"]
        for c in reg.discover().commands.values():
            self.assertIn(c.summary, commands)
        for k in reg.discover().kits:
            self.assertIn(f"=== {k}", out["docs-src/chapters/reference/kits.adoc"])
        for t in reg.discover().topics:
            self.assertIn(f"=== {t}", out["docs-src/chapters/reference/help-topics.adoc"])
        from ws_host.core import config
        for k in list(config.KEYS) + list(config.REPO_KEYS):
            self.assertIn(k, out["docs-src/chapters/reference/files.adoc"])

    def test_the_skill_says_decisions_are_for_a_person_and_lists_every_command(self):
        skill = reg.discover().generators["agent-skill"].render()[".claude/skills/ws-host/SKILL.md"]
        self.assertIn("`decision` category is for a person", skill)
        for c in reg.discover().commands.values():
            self.assertIn(f"`{c.id}`", skill)

    def test_a_change_to_a_topic_changes_the_reference(self):
        t = reg.discover().topics["start"]
        before = reg.discover().generators["reference-docs"].render()["docs-src/chapters/reference/help-topics.adoc"]
        saved = t.plain
        t.plain = "A different plain line."
        try:
            after = reg.discover().generators["reference-docs"].render()["docs-src/chapters/reference/help-topics.adoc"]
            self.assertNotEqual(before, after)
            self.assertEqual(self.run_json("fresh")[0], 1)
        finally:
            t.plain = saved


class Guide(Home):
    def test_the_graphics_of_the_earlier_environment_are_here_unchanged(self):
        expected = {"logo.png": "32375", "mascot.jpg": "183738", "mascot-workflows.jpg": "145214", "social-preview.jpg": "204239"}
        for name, size in expected.items():
            self.assertEqual(str((REPO / "docs" / name).stat().st_size), size, name)
        self.assertEqual((REPO / "docs" / "logo.png").read_bytes(), (REPO / "vscode" / "logo.png").read_bytes())
        self.assertIn("MIT License", (REPO / "docs" / "LICENSE-the earlier environment").read_text())
        self.assertIn("the earlier environment", (REPO / "docs-src" / "chapters" / "back-matter" / "colophon.adoc").read_text())

    def test_the_theme_files_are_here_and_the_book_uses_the_mascot(self):
        for f in ("html.css", "epub.css", "if-press-pdf-theme.yml"):
            self.assertTrue((REPO / "docs-src" / "theme" / f).is_file(), f)
        text = (REPO / "docs-src" / "chapters" / "front-matter" / "preface.adoc").read_text()
        self.assertIn("image::mascot.jpg", text)
        self.assertIn("image::mascot-workflows.jpg", text)
        self.assertIn("mascot.jpg", (REPO / "docs" / "index.html").read_text())

    def test_the_manuscript_includes_every_chapter_and_every_include_exists(self):
        ms = (REPO / "docs-src" / "manuscript.adoc").read_text()
        for inc in re.findall(r"include::([^\[]+)\[\]", ms):
            self.assertTrue((REPO / "docs-src" / inc).is_file(), inc)
        for f in (REPO / "docs-src" / "chapters").rglob("*.adoc"):
            self.assertIn(str(f.relative_to(REPO / "docs-src")), ms, f"{f} is not in the manuscript")

    def test_the_book_does_not_repeat_what_help_says_and_links_to_it(self):
        day = (REPO / "docs-src" / "chapters" / "overview" / "day-to-day.adoc").read_text()
        self.assertIn("ws-host help", day)
        self.assertIn("reference-help", day)
        for t in reg.discover().topics.values():
            for _h, text in t.sections:
                for para in text.split("\n"):
                    if len(para) > 120:
                        for f in (REPO / "docs-src" / "chapters" / "overview").glob("*.adoc"):
                            self.assertNotIn(para.strip(), f.read_text(), f"{f.name} repeats a help topic's paragraph")

    def test_the_shell_chapter_states_the_shell_policy_and_the_extend_chapter_the_python_strategy(self):
        shells = (REPO / "docs-src" / "chapters" / "overview" / "shells.adoc").read_text()
        for needle in ("`bash` and `oh-my-posh` are fully supported", "`fish` 4 is the best experience", "shell` kit", "never takes it for you"):
            self.assertIn(needle, shells)
        ext = (REPO / "docs-src" / "chapters" / "overview" / "extend-with-ai.adoc").read_text()
        for needle in ("AI", "Python module", "pyproject.toml", "uv.lock", "inside\nthe function that uses it", "dependency group"):
            self.assertIn(needle, ext)

    def test_the_book_is_in_the_documented_voice(self):
        banned = ("It is important to note", "It is worth mentioning", "In conclusion", "Let us begin", "At its core", "Before diving in")
        for f in (REPO / "docs-src").rglob("*.adoc"):
            for b in banned:
                self.assertNotIn(b, f.read_text(), f.name)

    def test_build_without_converters_says_which_are_missing_and_builds_nothing_it_cannot(self):
        bin_ = self.home.parent / "bin"
        bin_.mkdir()
        (bin_ / "asciidoctor").write_text('#!/bin/sh\ncase "$*" in *--version*) exit 1;; esac\nout=""\nwhile [ $# -gt 0 ]; do [ "$1" = -o ] && out=$2; shift; done\n[ -n "$out" ] && echo "<html></html>" > "$out"\nexit 0\n')
        (bin_ / "asciidoctor").chmod(0o755)
        keep = self.home.parent / "keep"
        keep.mkdir()
        for t in ("sh", "cat", "env"):
            shutil.copy(shutil.which(t), keep / t) if False else (keep / t).symlink_to(shutil.which(t))
        os.environ["PATH"] = f"{bin_}:{keep}"
        out = self.home / "site"
        code, doc = self.run_json("docs", "build", "--output", str(out))
        by = {e["name"]: e for e in doc["data"]["editions"]}
        self.assertEqual(by["single-page HTML"]["status"], "built")
        for name in ("multi-page HTML", "PDF", "EPUB"):
            self.assertEqual(by[name]["status"], "skipped", name)
            self.assertIn("not on this machine", by[name]["reason"])
        self.assertTrue((out / "book" / "single-page.html").is_file())
        self.assertTrue((out / "mascot.jpg").is_file() and (out / "index.html").is_file())
        self.assertEqual(code, 0)
        self.assertIn("Left out because a converter is missing", doc["data"]["plain"])
        self.assertEqual(doc["actions"][0]["cli"], "ws-host kit add press")
        self.assertFalse((REPO / "docs-src" / "theme" / "logo.png").exists())   # the repository is not touched

    def test_build_with_no_asciidoctor_names_the_press_kit(self):
        os.environ["PATH"] = str(self.home)
        code, doc = self.run_json("docs", "build")
        self.assertEqual((code, doc["data"]["code"]), (3, "missing-program"))
        self.assertEqual(doc["actions"][0]["cli"], "ws-host kit add press")

    def test_build_dry_run_changes_nothing(self):
        code, doc = self.run_json("docs", "build", "--output", str(self.home / "x"), "--dry-run")
        self.assertEqual(code, 0)
        self.assertFalse((self.home / "x").exists())
