"""Tab completion for bash and fish, generated from the registry (0006-onboarding FR-023).

The scripts hold the whole command tree, so completing a command or an option costs nothing. Only values that change while a person
works, such as the repositories they have, are asked of `ws-host completion list TYPE` at the moment Tab is pressed. Standard library only."""
from __future__ import annotations

from ..core import registry as reg
from ..core.cli import GLOBAL_FLAGS
from ..core.types import TYPES

HEADER = "generated by `ws-host completion add"      # a file that starts this way is ours to overwrite; any other is the person's
DYNAMIC = {"REPO"}                                   # asked at the moment Tab is pressed, because they change as a person works
NO_VALUES = {"COMMAND", "STRING", "PATH"}


def _flag(name: str) -> str:
    return "--" + name.lower().replace("_", "-")


def _values(arg) -> list[str]:
    if arg.choices:
        return list(arg.choices)
    t = TYPES.get(arg.type)
    if t is None or arg.type in NO_VALUES or arg.type in DYNAMIC:
        return []
    try:
        return [str(v) for v in t.complete(None)]
    except Exception:
        return []


def model(registry=None) -> dict:
    """The command tree: first words, each noun's verbs, each command's options and positional values."""
    registry = registry or reg.discover()
    first, verbs, commands = {}, {}, {}
    for words, c in sorted(registry.commands.items()):
        if c.noun:
            first.setdefault(c.noun, f"{c.noun} commands")
            verbs.setdefault(c.noun, {})[c.verb] = c.summary
        else:
            first[c.verb] = c.summary
        opts = {_flag(a.name): (not a.flag, a.help or a.name) for a in c.args if not a.positional}
        if c.writes:
            opts["--dry-run"] = (False, "show what would change, and change nothing")
        if c.category == "decision":
            opts["--confirmed"] = (False, "you confirmed this in the editor")
        opts["--debug"] = (False, "show technical detail")
        opts["--offline"] = (False, "do not use the network")
        for g in GLOBAL_FLAGS:
            opts[g] = (False, "machine-readable output" if g == "--json" else "an HTML page")
        pos = [{"type": a.type, "values": _values(a), "dynamic": a.type in DYNAMIC, "multiple": a.multiple} for a in c.args if a.positional]
        commands[c.id] = {"options": opts, "positionals": pos}
    value_options = sorted({o for c in commands.values() for o, (takes, _) in c["options"].items() if takes})
    return {"first": first, "verbs": verbs, "commands": commands, "value_options": value_options}


def _q(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


def bash(m: dict) -> str:
    out = [f"# bash completion for ws-host, {HEADER} bash`; it is overwritten when ws-host updates it.",
           "_ws_host() {",
           '  local cur="${COMP_WORDS[COMP_CWORD]}" i w skip=0 key pos n noun=0 opts vals',
           "  local -a words=()",
           "  for ((i = 1; i < COMP_CWORD; i++)); do",
           '    w="${COMP_WORDS[i]}"',
           '    if [ "$skip" = 1 ]; then skip=0; continue; fi',
           '    case "$w" in',
           f"      {'|'.join(m['value_options'])}) skip=1 ;;" if m["value_options"] else "      --nothing-takes-a-value) ;;",
           "      -*) ;;",
           '      *) words+=("$w") ;;',
           "    esac",
           "  done",
           '  n=${#words[@]}',
           '  if [ "$n" = 0 ]; then',
           '    case "$cur" in',
           '      -*) COMPREPLY=($(compgen -W "--help --version" -- "$cur")) ;;',
           f'      *) COMPREPLY=($(compgen -W "{" ".join(sorted(m["first"]))}" -- "$cur")) ;;',
           "    esac",
           "    return",
           "  fi",
           '  case "${words[0]}" in',
           f"    {'|'.join(sorted(m['verbs']))}) noun=1 ;;" if m["verbs"] else "    --none) ;;",
           "  esac",
           '  if [ "$noun" = 1 ]; then',
           '    if [ "$n" = 1 ]; then',
           '      case "${words[0]}" in']
    for noun, vs in sorted(m["verbs"].items()):
        out.append(f'        {noun}) vals="{" ".join(sorted(vs))}" ;;')
    out += ["      esac",
            '      COMPREPLY=($(compgen -W "$vals" -- "$cur"))',
            "      return",
            "    fi",
            '    key="${words[0]} ${words[1]}"; pos=$((n - 2))',
            "  else",
            '    key="${words[0]}"; pos=$((n - 1))',
            "  fi",
            '  case "$cur" in',
            "    -*)",
            '      case "$key" in']
    for cid, c in sorted(m["commands"].items()):
        out.append(f'        "{cid}") opts="{" ".join(sorted(c["options"]))}" ;;')
    out += ['        *) opts="--json --html --debug --offline" ;;',
            "      esac",
            '      COMPREPLY=($(compgen -W "$opts" -- "$cur"))',
            "      return ;;",
            "  esac",
            '  case "$key:$pos" in']
    for cid, c in sorted(m["commands"].items()):
        for i, p in enumerate(c["positionals"]):
            last = i == len(c["positionals"]) - 1 and p["multiple"]
            pat = " | ".join(f'"{cid}:{k}"' for k in (range(i, i + 8) if last else (i,)))
            if p["dynamic"]:
                out.append(f'    {pat}) vals="$(ws-host completion list {p["type"]} 2>/dev/null | sed -n \'s/^  - //p\')" ;;')
            elif p["values"]:
                out.append(f'    {pat}) vals="{" ".join(p["values"])}" ;;')
    out += ['    *) vals="" ;;',
            "  esac",
            '  COMPREPLY=($(compgen -W "$vals" -- "$cur"))',
            "}",
            "complete -F _ws_host ws-host",
            ""]
    return "\n".join(out)


def fish(m: dict) -> str:
    vo = " ".join(_q(o) for o in m["value_options"]) or "''"
    nouns = " ".join(sorted(m["verbs"]))
    out = [f"# fish completion for ws-host, {HEADER} fish`; it is overwritten when ws-host updates it.",
           "function __ws_host_words",
           "    set -l skip 0",
           "    for t in (commandline -opc)[2..-1]",
           "        if test $skip = 1",
           "            set skip 0",
           "            continue",
           "        end",
           "        if contains -- $t " + vo,
           "            set skip 1",
           "            continue",
           "        end",
           "        string match -q -- '-*' $t; and continue",
           "        echo $t",
           "    end",
           "end",
           "function __ws_host_key",
           "    set -l w (__ws_host_words)",
           f"    if contains -- $w[1] {nouns}" if nouns else "    if false",
           "        echo $w[1] $w[2]",
           "    else",
           "        echo $w[1]",
           "    end",
           "end",
           "function __ws_host_count --argument-names n",
           "    test (count (__ws_host_words)) -eq $n",
           "end",
           "function __ws_host_noun --argument-names noun",
           "    set -l w (__ws_host_words)",
           "    test (count $w) -eq 1; and test \"$w[1]\" = $noun",
           "end",
           "function __ws_host_pos --argument-names key idx plus",
           "    set -l w (__ws_host_words)",
           "    test (count $w) -ge 1; or return 1",
           "    set -l k (__ws_host_key)",
           "    test \"$k\" = \"$key\"; or return 1",
           "    set -l done (count (string split ' ' $key))",
           "    set -l have (math (count $w) - $done)",
           "    if test -n \"$plus\"",
           "        test $have -ge $idx",
           "    else",
           "        test $have -eq $idx",
           "    end",
           "end",
           "function __ws_host_cmd --argument-names key",
           "    test (count (__ws_host_words)) -ge (count (string split ' ' $key)); and test (__ws_host_key) = $key",
           "end",
           "complete -c ws-host -f"]
    for word, summary in sorted(m["first"].items()):
        out.append(f"complete -c ws-host -n '__ws_host_count 0' -a {_q(word)} -d {_q(summary)}")
    for noun, vs in sorted(m["verbs"].items()):
        for verb, summary in sorted(vs.items()):
            out.append(f"complete -c ws-host -n '__ws_host_noun {noun}' -a {_q(verb)} -d {_q(summary)}")
    for cid, c in sorted(m["commands"].items()):
        for flag, (takes, hlp) in sorted(c["options"].items()):
            out.append(f"complete -c ws-host -n {_q('__ws_host_cmd ' + _q(cid))} -l {flag[2:]} -d {_q(hlp)}" + (" -r" if takes else ""))
        for i, p in enumerate(c["positionals"]):
            plus = " plus" if i == len(c["positionals"]) - 1 and p["multiple"] else ""
            cond = f"__ws_host_pos {_q(cid)} {i}{plus}"
            if p["dynamic"]:
                out.append(f"complete -c ws-host -n {_q(cond)} -a '(command -q ws-host; and ws-host completion list {p['type']} 2>/dev/null | string replace -rf \"^  - \" \"\")'")
            elif p["values"]:
                out.append(f"complete -c ws-host -n {_q(cond)} -a {_q(' '.join(p['values']))}")
    out.append("")
    return "\n".join(out)


def target(shell: str):
    """Where each shell looks for completions on its own, so no startup file needs a line."""
    import os
    from pathlib import Path
    from ..core import paths
    if shell == "bash":
        xdg = os.environ.get("XDG_DATA_HOME")
        return (Path(xdg) if xdg and os.path.isabs(xdg) else paths.home() / ".local" / "share") / "bash-completion" / "completions" / "ws-host"
    xdg = os.environ.get("XDG_CONFIG_HOME")
    return (Path(xdg) if xdg and os.path.isabs(xdg) else paths.home() / ".config") / "fish" / "completions" / "ws-host.fish"


def install(shell: str, dry_run: bool = False) -> dict:
    """Write the completion script where `shell` finds it. Overwrites only a file this command wrote; a person's own is left alone."""
    f = target(shell)
    text = (bash if shell == "bash" else fish)(model())
    old = f.read_text(encoding="utf-8") if f.is_file() else None
    if old is not None and HEADER not in old.splitlines()[0]:
        return {"shell": shell, "file": str(f), "status": "left-alone", "changed": False,
                "plain": f"{f} is not one I wrote, so I left it alone. Delete it and run this again to use mine."}
    changed = old != text
    if changed and not dry_run:
        f.parent.mkdir(parents=True, exist_ok=True)
        tmp = f.with_name(f".{f.name}.ws-host.new")
        tmp.write_text(text, encoding="utf-8")
        import os
        os.replace(tmp, f)
    return {"shell": shell, "file": str(f), "status": "would-write" if changed and dry_run else "written" if changed else "current", "changed": changed,
            "plain": f"Tab completion for {shell} is set up. It starts in a new terminal window." if changed else f"Tab completion for {shell} was already up to date."}
