"""Providers and their declarations (0008-providers): `.workspaces-host/provider.toml` and `.workspaces-host/toolchain.d/*.toml`, read as data.

Nothing in this module runs a provider's code. It reads TOML with the standard library, checks it, and writes the `mise` configuration that
`ws-host` installs from; `lib/mise.py` runs `mise`."""
from __future__ import annotations

import json
import os
import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

from ..core import paths

FOLDER = ".workspaces-host"
PLATFORMS = ("linux-x64", "linux-arm64")
KINDS = ("archive", "npm", "tool")
NAME_RE = re.compile(r"[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*")
VERSION_RE = re.compile(r"\d+(?:\.\d+)*(?:[+-][A-Za-z0-9._+-]*)?")
SHA_RE = re.compile(r"[0-9a-f]{64}")
FLOATING = ("latest", "stable", "head", "main", "master", "next", "nightly", "lts")
GENERATED = "# Generated by `ws-host toolchain generate` from {source}. Do not edit it; change the entry and run that command again."


@dataclass
class Problem:
    where: str
    message: str

    def __str__(self) -> str:
        return f"{self.where}: {self.message}"


@dataclass
class Entry:
    name: str
    version: str
    summary: str
    kind: str
    file: str
    platforms: dict[str, dict[str, str]] = field(default_factory=dict)
    strip: int = 1
    bin: str | None = None
    bins: dict[str, str] = field(default_factory=dict)
    provides: dict[str, str] = field(default_factory=dict)
    env: dict[str, str] = field(default_factory=dict)
    needs: list[str] = field(default_factory=list)
    system: list[str] = field(default_factory=list)
    package: str = ""
    tool: str = ""

    def tool_id(self) -> str:
        """The name `mise` knows this entry by."""
        return {"archive": f"http:{self.name}", "npm": f"npm:{self.package}", "tool": self.tool}[self.kind]

    def signature(self) -> str:
        """What makes two declarations of one name and version the same program (0008-providers FR-009)."""
        return json.dumps({"kind": self.kind, "platforms": self.platforms, "package": self.package, "tool": self.tool,
                           "strip": self.strip, "bin": self.bin, "bins": self.bins}, sort_keys=True)

    def bin_dir(self, platform: str) -> str | None:
        """The folder, relative to the unpacked root, whose programs go on PATH on this platform; None when none does."""
        return self.bins.get(platform, self.bin)


@dataclass
class Provider:
    name: str
    summary: str
    launcher: str
    root: Path
    protocol: int = 1
    entries: dict[str, Entry] = field(default_factory=dict)
    problems: list[Problem] = field(default_factory=list)

    @property
    def folder(self) -> Path:
        return self.root / FOLDER

    @property
    def mise_dir(self) -> Path:
        return self.folder / "mise"


def _read(path: Path, problems: list[Problem], where: str) -> dict:
    try:
        with open(path, "rb") as f:
            return tomllib.load(f)
    except OSError as e:
        problems.append(Problem(where, f"cannot be read: {e.strerror or e}"))
    except tomllib.TOMLDecodeError as e:
        problems.append(Problem(where, f"is not valid TOML: {e}"))
    return {}


def _str(d: dict, key: str, where: str, problems: list[Problem], required: bool = True) -> str:
    v = d.get(key)
    if v is None:
        if required:
            problems.append(Problem(where, f"is missing '{key}'"))
        return ""
    if not isinstance(v, str) or not v.strip():
        problems.append(Problem(where, f"'{key}' must be a non-empty string"))
        return ""
    return v


def platform() -> str:
    """This machine's platform name in declarations."""
    import platform as _p
    return "linux-arm64" if _p.machine().lower() in ("aarch64", "arm64") else "linux-x64"


def _entry(path: Path, rel: str, problems: list[Problem]) -> Entry | None:
    raw = _read(path, problems, rel)
    if not raw:
        return None
    name = _str(raw, "name", rel, problems)
    if name and (not NAME_RE.fullmatch(name) or name != path.stem):
        problems.append(Problem(rel, f"'name' is {name!r} but the file is {path.stem}.toml; they must be the same and made of letters, digits and hyphens"))
    version = _str(raw, "version", rel, problems)
    if version and (not VERSION_RE.fullmatch(version) or version.lower() in FLOATING or any(c in version for c in "<>=~^*, ")):
        problems.append(Problem(rel, f"'version' is {version!r}; it must be one exact version, not a range or a floating tag"))
    summary = _str(raw, "summary", rel, problems)
    kind = _str(raw, "kind", rel, problems)
    if kind and kind not in KINDS:
        problems.append(Problem(rel, f"'kind' is {kind!r}; it must be one of {', '.join(KINDS)}"))
    e = Entry(name=name or path.stem, version=version, summary=summary, kind=kind, file=rel)
    if kind == "archive":
        platforms = raw.get("platforms")
        if not isinstance(platforms, dict) or "linux-x64" not in platforms:
            problems.append(Problem(rel, "needs a [platforms.linux-x64] table with a url and a sha256"))
            platforms = platforms if isinstance(platforms, dict) else {}
        for plat, p in platforms.items():
            at = f"{rel} [platforms.{plat}]"
            if plat not in PLATFORMS:
                problems.append(Problem(at, f"is not a platform ({', '.join(PLATFORMS)})"))
                continue
            if not isinstance(p, dict):
                problems.append(Problem(at, "must be a table"))
                continue
            url, sha = _str(p, "url", at, problems), _str(p, "sha256", at, problems)
            if url and not url.startswith("https://"):
                problems.append(Problem(at, f"'url' {url!r} is not an https address"))
            if sha and not SHA_RE.fullmatch(sha):
                problems.append(Problem(at, "'sha256' is not 64 hexadecimal digits"))
            e.platforms[plat] = {"url": url, "sha256": sha}
            if "bin" in p:
                e.bins[plat] = str(p["bin"])
        strip = raw.get("strip", 1)
        if not isinstance(strip, int) or isinstance(strip, bool) or strip < 0:
            problems.append(Problem(rel, "'strip' must be a whole number of path parts, 0 or more"))
        else:
            e.strip = strip
    elif kind == "npm":
        e.package = _str(raw, "package", rel, problems)
    elif kind == "tool":
        e.tool = _str(raw, "tool", rel, problems)
    e.bin = str(raw["bin"]) if "bin" in raw else None
    for key in ("provides", "env"):
        val = raw.get(key, {})
        if not isinstance(val, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in val.items()):
            problems.append(Problem(rel, f"'{key}' must be a table of text"))
        else:
            setattr(e, key, dict(val))
    system = raw.get("system", [])
    if not isinstance(system, list) or not all(isinstance(x, str) for x in system):
        problems.append(Problem(rel, "'system' must be a list of package names"))
    else:
        e.system = list(system)
    needs = raw.get("needs", [])
    if not isinstance(needs, list) or not all(isinstance(n, str) for n in needs):
        problems.append(Problem(rel, "'needs' must be a list of entry names"))
    else:
        e.needs = list(needs)
    return e


def load(root: Path) -> Provider | None:
    """Read a provider's declarations; None when `root` declares none. Problems are collected, never raised."""
    f = root / FOLDER / "provider.toml"
    if not f.is_file():
        return None
    problems: list[Problem] = []
    where = f"{FOLDER}/provider.toml"
    raw = _read(f, problems, where)
    name = _str(raw, "name", where, problems)
    if name and not NAME_RE.fullmatch(name):
        problems.append(Problem(where, f"'name' is {name!r}; it must be letters, digits and hyphens"))
    launcher = _str(raw, "launcher", where, problems)
    if launcher:
        m = re.fullmatch(r"\./([A-Za-z0-9._-]+)", launcher)
        if not m:
            problems.append(Problem(where, f"'launcher' is {launcher!r}; it must be a file at the repository's root written ./name"))
        elif not os.access(root / m.group(1), os.X_OK) or not (root / m.group(1)).is_file():
            problems.append(Problem(where, f"'launcher' {launcher} is not an executable file at the repository's root"))
    protocol = raw.get("protocol")
    if protocol != 1:
        problems.append(Problem(where, f"'protocol' is {protocol!r}; this ws-host speaks protocol 1"))
    p = Provider(name=name, summary=_str(raw, "summary", where, problems), launcher=launcher, root=root, protocol=1)
    d = root / FOLDER / "toolchain.d"
    for path in sorted(d.glob("*.toml")) if d.is_dir() else []:
        e = _entry(path, f"{FOLDER}/toolchain.d/{path.name}", problems)
        if e is not None:
            p.entries[e.name] = e
    for e in p.entries.values():
        for n in e.needs:
            if n not in p.entries:
                problems.append(Problem(e.file, f"'needs' names {n!r}, which is not an entry of this provider"))
    problems += _cycles(p)
    p.problems = problems
    return p


def _cycles(p: Provider) -> list[Problem]:
    out, state = [], {}

    def visit(n: str, trail: list[str]) -> None:
        if state.get(n) == 2 or n not in p.entries:
            return
        if state.get(n) == 1:
            out.append(Problem(p.entries[n].file, "'needs' forms a cycle: " + " -> ".join(trail[trail.index(n):] + [n])))
            return
        state[n] = 1
        for m in p.entries[n].needs:
            visit(m, trail + [n])
        state[n] = 2

    for n in sorted(p.entries):
        visit(n, [])
    return out


# ---- the translation ---------------------------------------------------------------------------------------------------

def _q(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def translate(p: Provider) -> dict[str, str]:
    """The `mise` configuration for a provider's entries, by path under `.workspaces-host/mise/` (0008-providers FR-006)."""
    out = {".config/mise/conf.d/00-settings.toml": "\n".join([
        GENERATED.format(source=f"{FOLDER}/toolchain.d"), "[settings]", "lockfile = true", ""])}
    for name, e in sorted(p.entries.items()):
        head = GENERATED.format(source=f"{FOLDER}/toolchain.d/{name}.toml")
        if e.kind == "archive":
            lines = [head, f"[tools.{_q(e.tool_id())}]", f"version = {_q(e.version)}", f"strip_components = {e.strip}"]
            lines.append(f"[tools.{_q(e.tool_id())}.platforms]")
            for plat in PLATFORMS:
                if plat in e.platforms:
                    pl = e.platforms[plat]
                    lines.append(f'{plat} = {{ url = {_q(pl["url"])}, checksum = "sha256:{pl["sha256"]}" }}')
        else:
            lines = [head, "[tools]", f"{_q(e.tool_id())} = {_q(e.version)}"]
        out[f".config/mise/conf.d/{name}.toml"] = "\n".join(lines) + "\n"
    return out


def stale(p: Provider) -> list[str]:
    """The generated files that differ from what the entries say now, and generated files whose entry is gone."""
    want = translate(p)
    found = []
    for rel, text in want.items():
        f = p.mise_dir / rel
        if not f.is_file() or f.read_text(encoding="utf-8") != text:
            found.append(f"{FOLDER}/mise/{rel}")
    d = p.mise_dir / ".config/mise/conf.d"
    for f in sorted(d.glob("*.toml")) if d.is_dir() else []:
        if f".config/mise/conf.d/{f.name}" not in want:
            found.append(f"{FOLDER}/mise/.config/mise/conf.d/{f.name}")
    return found


def write(p: Provider) -> list[str]:
    """Write the translation; returns the files that changed. Removes generated files whose entry is gone."""
    want = translate(p)
    changed = []
    for rel, text in want.items():
        f = p.mise_dir / rel
        if not f.is_file() or f.read_text(encoding="utf-8") != text:
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(text, encoding="utf-8")
            changed.append(f"{FOLDER}/mise/{rel}")
    d = p.mise_dir / ".config/mise/conf.d"
    for f in sorted(d.glob("*.toml")) if d.is_dir() else []:
        if f".config/mise/conf.d/{f.name}" not in want:
            f.unlink()
            changed.append(f"{FOLDER}/mise/.config/mise/conf.d/{f.name} (removed)")
    return changed


# ---- enabled providers ----------------------------------------------------------------------------------------------------

def providers_dir() -> Path:
    return paths.config_dir() / "providers.d"


def explicit() -> list[Provider]:
    """The providers a person enabled with `provider add`: the links in their providers folder; a link that no longer leads to a provider is skipped."""
    out = []
    d = providers_dir()
    for link in sorted(d.iterdir()) if d.is_dir() else []:
        folder = Path(os.path.realpath(link))
        if folder.name != FOLDER:
            continue
        p = load(folder.parent)
        if p is not None and p.name == link.name:
            out.append(p)
    return out


def implicit() -> dict[str, tuple[Provider, str]]:
    """The providers that need no `provider add`, with why (0008-providers FR-010): the clone of ws-host that is running, which is the code the person
    installed, and every cloned repository the person trusts (0002 FR-012), which includes the organization ws-host itself comes from."""
    out: dict[str, tuple[Provider, str]] = {}
    if os.environ.get("WS_HOST_IMPLICIT") == "no":      # the tests' own homes, where nothing is in use until a test enables it
        return out
    own = load(paths.repo_root())
    if own is not None and not own.problems:
        out[own.name] = (own, "this is the ws-host you are running")
    try:
        from ..core import config
        from . import repos, trust
        cfg = config.load()
        for rid in sorted(repos.known(cfg)[0], key=str):
            if not (rid.path(cfg) / FOLDER / "provider.toml").is_file():
                continue
            ok, why = trust.trust_state(rid, cfg)
            p = load(rid.path(cfg)) if ok else None
            if p is not None and p.name not in out:
                out[p.name] = (p, why)
    except Exception:             # a broken configuration must not stop a provider that was enabled by hand
        pass
    return out


def enabled() -> list[Provider]:
    """Every provider in use, in name order: the ones a person enabled by hand, then those that need no enabling (see `implicit`); by hand wins a name."""
    by_name = {p.name: p for p in explicit()}
    for name, (p, _why) in implicit().items():
        by_name.setdefault(name, p)
    return [by_name[n] for n in sorted(by_name)]


def how_enabled(name: str) -> str:
    """Why a provider is in use, in plain words."""
    if any(p.name == name for p in explicit()):
        return "you enabled it"
    return implicit().get(name, (None, "not enabled"))[1]


def conflicts(providers: list[Provider]) -> list[str]:
    """Two providers declaring one entry name and version differently (0008-providers FR-009), one sentence for each pair."""
    seen: dict[tuple[str, str], tuple[str, str]] = {}
    out = []
    for p in sorted(providers, key=lambda x: x.name):
        for e in p.entries.values():
            key = (e.name, e.version)
            sig = e.signature()
            if key in seen and seen[key][1] != sig:
                out.append(f"{seen[key][0]} and {p.name} both declare {e.name} {e.version}, but not the same file; give one of them another name or version")
            seen.setdefault(key, (p.name, sig))
    return out


def get(name: str) -> Provider | None:
    for p in enabled():
        if p.name == name:
            return p
    return None
