# fish completion for ws-host, generated by `ws-host completion add fish`; it is overwritten when ws-host updates it.
function __ws_host_words
    set -l skip 0
    for t in (commandline -opc)[2..-1]
        if test $skip = 1
            set skip 0
            continue
        end
        if contains -- $t '--host' '--output' '--suite'
            set skip 1
            continue
        end
        string match -q -- '-*' $t; and continue
        echo $t
    end
end
function __ws_host_key
    set -l w (__ws_host_words)
    if contains -- $w[1] auth command completion docs kit repo shell skill vscode workspace
        echo $w[1] $w[2]
    else
        echo $w[1]
    end
end
function __ws_host_count --argument-names n
    test (count (__ws_host_words)) -eq $n
end
function __ws_host_noun --argument-names noun
    set -l w (__ws_host_words)
    test (count $w) -eq 1; and test "$w[1]" = $noun
end
function __ws_host_pos --argument-names key idx plus
    set -l w (__ws_host_words)
    test (count $w) -ge 1; or return 1
    set -l k (__ws_host_key)
    test "$k" = "$key"; or return 1
    set -l done (count (string split ' ' $key))
    set -l have (math (count $w) - $done)
    if test -n "$plus"
        test $have -ge $idx
    else
        test $have -eq $idx
    end
end
function __ws_host_cmd --argument-names key
    test (count (__ws_host_words)) -ge (count (string split ' ' $key)); and test (__ws_host_key) = $key
end
complete -c ws-host -f
complete -c ws-host -n '__ws_host_count 0' -a 'auth' -d 'auth commands'
complete -c ws-host -n '__ws_host_count 0' -a 'check' -d 'Run the checks of this repository'
complete -c ws-host -n '__ws_host_count 0' -a 'command' -d 'command commands'
complete -c ws-host -n '__ws_host_count 0' -a 'completion' -d 'completion commands'
complete -c ws-host -n '__ws_host_count 0' -a 'context' -d 'Everything needed to get help with this machine, with secrets removed'
complete -c ws-host -n '__ws_host_count 0' -a 'docs' -d 'docs commands'
complete -c ws-host -n '__ws_host_count 0' -a 'doctor' -d 'Check what ws-host needs and what is present'
complete -c ws-host -n '__ws_host_count 0' -a 'fresh' -d 'Prove the generated files are current'
complete -c ws-host -n '__ws_host_count 0' -a 'help' -d 'Learn how to do the daily work, one topic at a time'
complete -c ws-host -n '__ws_host_count 0' -a 'kit' -d 'kit commands'
complete -c ws-host -n '__ws_host_count 0' -a 'repo' -d 'repo commands'
complete -c ws-host -n '__ws_host_count 0' -a 'shell' -d 'shell commands'
complete -c ws-host -n '__ws_host_count 0' -a 'skill' -d 'skill commands'
complete -c ws-host -n '__ws_host_count 0' -a 'test' -d 'Run this repository'\''s tests'
complete -c ws-host -n '__ws_host_count 0' -a 'update' -d 'Move ws-host to its newest version, only when nothing of yours is in the way; --check only looks'
complete -c ws-host -n '__ws_host_count 0' -a 'vscode' -d 'vscode commands'
complete -c ws-host -n '__ws_host_count 0' -a 'workspace' -d 'workspace commands'
complete -c ws-host -n '__ws_host_noun auth' -a 'new' -d 'Sign in to GitHub or GitLab with a one-time code'
complete -c ws-host -n '__ws_host_noun auth' -a 'status' -d 'Say whether you are signed in to GitHub and GitLab'
complete -c ws-host -n '__ws_host_noun command' -a 'list' -d 'List every command'
complete -c ws-host -n '__ws_host_noun command' -a 'show' -d 'Show one command in full'
complete -c ws-host -n '__ws_host_noun completion' -a 'add' -d 'Set up Tab completion for ws-host in bash or fish'
complete -c ws-host -n '__ws_host_noun completion' -a 'list' -d 'List the values an argument can take, which is what Tab offers'
complete -c ws-host -n '__ws_host_noun docs' -a 'build' -d 'Build the guide: HTML, PDF and, where the converter is here, EPUB'
complete -c ws-host -n '__ws_host_noun docs' -a 'generate' -d 'Rewrite the guide'\''s generated reference chapters'
complete -c ws-host -n '__ws_host_noun kit' -a 'add' -d 'Install a kit (uses sudo for packages, and says so first)'
complete -c ws-host -n '__ws_host_noun kit' -a 'list' -d 'List the kits and which are installed'
complete -c ws-host -n '__ws_host_noun kit' -a 'show' -d 'Show what a kit installs on this machine'
complete -c ws-host -n '__ws_host_noun repo' -a 'add' -d 'Copy missing repositories to this machine'
complete -c ws-host -n '__ws_host_noun repo' -a 'list' -d 'List the repositories I know'
complete -c ws-host -n '__ws_host_noun repo' -a 'set' -d 'Trust or stop trusting a repository'\''s code'
complete -c ws-host -n '__ws_host_noun repo' -a 'status' -d 'Show the state of one or all repositories'
complete -c ws-host -n '__ws_host_noun repo' -a 'sync' -d 'Bring repositories up to date, never touching your work'
complete -c ws-host -n '__ws_host_noun shell' -a 'add' -d 'Give bash or fish the ws-host oh-my-posh prompt (again, or the plain one)'
complete -c ws-host -n '__ws_host_noun skill' -a 'generate' -d 'Rewrite the skill that tells an AI agent how to use ws-host'
complete -c ws-host -n '__ws_host_noun vscode' -a 'ensure' -d 'Put VS Code in its recommended state: the IF Console, helpful extensions and safe settings'
complete -c ws-host -n '__ws_host_noun workspace' -a 'ensure' -d 'Install your kits, check sign-in, copy missing repositories, update the rest, set up the editor, check health'
complete -c ws-host -n '__ws_host_noun workspace' -a 'set' -d 'Make git'\''s Sync button safe: set pull.ff to only'
complete -c ws-host -n '__ws_host_noun workspace' -a 'status' -d 'Say how this machine and your repositories stand'
complete -c ws-host -n '__ws_host_cmd '\''auth new'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''auth new'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''auth new'\''' -l host -d 'the host, for a GitLab other than the first configured' -r
complete -c ws-host -n '__ws_host_cmd '\''auth new'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''auth new'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''auth new'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_pos '\''auth new'\'' 0' -a 'github gitlab'
complete -c ws-host -n '__ws_host_cmd '\''auth status'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''auth status'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''auth status'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''auth status'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''check'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''check'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''check'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''check'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''check'\''' -l suite -d 'a named set of sections' -r
complete -c ws-host -n '__ws_host_pos '\''check'\'' 0 plus' -a 'console fresh help launcher registry specs'
complete -c ws-host -n '__ws_host_cmd '\''command list'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''command list'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''command list'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''command list'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''command show'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''command show'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''command show'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''command show'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''completion add'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''completion add'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''completion add'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''completion add'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''completion add'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_pos '\''completion add'\'' 0' -a 'bash fish'
complete -c ws-host -n '__ws_host_cmd '\''completion list'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''completion list'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''completion list'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''completion list'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''context'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''context'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''context'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''context'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''docs build'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''docs build'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''docs build'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''docs build'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''docs build'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''docs build'\''' -l output -d 'where to put it (default _site)' -r
complete -c ws-host -n '__ws_host_cmd '\''docs generate'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''docs generate'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''docs generate'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''docs generate'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''docs generate'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''doctor'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''doctor'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''doctor'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''doctor'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''fresh'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''fresh'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''fresh'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''fresh'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''help'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''help'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''help'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''help'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_pos '\''help'\'' 0' -a 'ai editor extend kits recover repos shell signin start trust update workspace-file'
complete -c ws-host -n '__ws_host_cmd '\''kit add'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''kit add'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''kit add'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''kit add'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''kit add'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_pos '\''kit add'\'' 0' -a 'base press rust shell'
complete -c ws-host -n '__ws_host_cmd '\''kit list'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''kit list'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''kit list'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''kit list'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''kit show'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''kit show'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''kit show'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''kit show'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_pos '\''kit show'\'' 0' -a 'base press rust shell'
complete -c ws-host -n '__ws_host_cmd '\''repo add'\''' -l all -d 'every known repository'
complete -c ws-host -n '__ws_host_cmd '\''repo add'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''repo add'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''repo add'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''repo add'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''repo add'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''repo add'\''' -l trust -d 'also trust them'
complete -c ws-host -n '__ws_host_pos '\''repo add'\'' 0' -a '(command -q ws-host; and ws-host completion list REPO 2>/dev/null | string replace -rf "^  - " "")'
complete -c ws-host -n '__ws_host_cmd '\''repo list'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''repo list'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''repo list'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''repo list'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''repo set'\''' -l confirmed -d 'you confirmed this in the editor'
complete -c ws-host -n '__ws_host_cmd '\''repo set'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''repo set'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''repo set'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''repo set'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''repo set'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''repo set'\''' -l trusted -d 'trusted'
complete -c ws-host -n '__ws_host_cmd '\''repo set'\''' -l untrusted -d 'untrusted'
complete -c ws-host -n '__ws_host_pos '\''repo set'\'' 0' -a '(command -q ws-host; and ws-host completion list REPO 2>/dev/null | string replace -rf "^  - " "")'
complete -c ws-host -n '__ws_host_cmd '\''repo status'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''repo status'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''repo status'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''repo status'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_pos '\''repo status'\'' 0' -a '(command -q ws-host; and ws-host completion list REPO 2>/dev/null | string replace -rf "^  - " "")'
complete -c ws-host -n '__ws_host_cmd '\''repo sync'\''' -l all -d 'every cloned repository'
complete -c ws-host -n '__ws_host_cmd '\''repo sync'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''repo sync'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''repo sync'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''repo sync'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''repo sync'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_pos '\''repo sync'\'' 0' -a '(command -q ws-host; and ws-host completion list REPO 2>/dev/null | string replace -rf "^  - " "")'
complete -c ws-host -n '__ws_host_cmd '\''shell add'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''shell add'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''shell add'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''shell add'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''shell add'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''shell add'\''' -l plain -d 'use ws-host-plain, which needs no Nerd Font'
complete -c ws-host -n '__ws_host_pos '\''shell add'\'' 0' -a 'bash fish'
complete -c ws-host -n '__ws_host_cmd '\''skill generate'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''skill generate'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''skill generate'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''skill generate'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''skill generate'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''test'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''test'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''test'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''test'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''update'\''' -l background -d 'with --check: look quietly and leave a note for new terminal windows'
complete -c ws-host -n '__ws_host_cmd '\''update'\''' -l cached -d 'with --check: do not use the network; say what the last look found'
complete -c ws-host -n '__ws_host_cmd '\''update'\''' -l check -d 'only look for a newer version and say what is new; change nothing'
complete -c ws-host -n '__ws_host_cmd '\''update'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''update'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''update'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''update'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''update'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''vscode ensure'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''vscode ensure'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''vscode ensure'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''vscode ensure'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''vscode ensure'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''workspace ensure'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''workspace ensure'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''workspace ensure'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''workspace ensure'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''workspace ensure'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''workspace set'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''workspace set'\''' -l dry-run -d 'show what would change, and change nothing'
complete -c ws-host -n '__ws_host_cmd '\''workspace set'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''workspace set'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''workspace set'\''' -l offline -d 'do not use the network'
complete -c ws-host -n '__ws_host_cmd '\''workspace set'\''' -l pull-ff-only -d 'set git'\''s pull.ff to only'
complete -c ws-host -n '__ws_host_cmd '\''workspace status'\''' -l debug -d 'show technical detail'
complete -c ws-host -n '__ws_host_cmd '\''workspace status'\''' -l html -d 'an HTML page'
complete -c ws-host -n '__ws_host_cmd '\''workspace status'\''' -l json -d 'machine-readable output'
complete -c ws-host -n '__ws_host_cmd '\''workspace status'\''' -l offline -d 'do not use the network'
