"""`docs generate`, `docs build`, `skill generate` and `fresh`: the generated reference, the guide, the agent skill
(0005-help-and-docs FR-006, FR-007, FR-013, FR-014, 0041-command-line FR-035, FR-036)."""
from __future__ import annotations

import html
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from .. import NAME, VERSION
from ..core import config, paths, registry as reg
from ..core.registry import Arg, command, generator, section
from ..core.resource import Action, FAILED, MISSING, OK, Resource, WsError, command_line, wire_surfaces
from . import command as command_cmd

DEBIAN = {"id": "debian", "id_like": "", "codename": "trixie", "version": "13", "arch": "x86_64"}
UBUNTU = {"id": "ubuntu", "id_like": "debian", "codename": "noble", "version": "24.04", "arch": "x86_64"}


def header(kind: str, name: str, command_: str) -> str:
    text = f"Generated by {NAME}: {name}. Rewrite it with `{NAME} {command_}`; do not edit it by hand."
    return f"// {text}\n" if kind == "adoc" else f"<!-- {text} -->\n"


def _cell(s) -> str:
    return str(s).replace("|", "\\|")


@generator("reference-docs", "docs generate", "the guide's reference chapters: commands, kits, files and help topics")
def reference_docs() -> dict:
    h = lambda: header("adoc", "reference-docs", "docs generate")
    r = reg.discover()
    out = {}

    # commands
    lines = [h(), "[#reference-commands]", "== Command reference", "",
             f"Every command, taken from the registry. `{NAME} command list` and `{NAME} command show ID` say the same thing, and "
             f"`{NAME} help` is where the daily work is explained.", ""]
    cmds = sorted(r.commands.values(), key=lambda c: (c.noun or "", c.id))
    groups: dict = {}
    for c in cmds:
        groups.setdefault(c.noun or "(no noun: the repository-wide commands)", []).append(c)
    for noun, items in sorted(groups.items(), key=lambda kv: (kv[0].startswith("("), kv[0])):
        lines += [f"=== {noun}", "", '[cols="3,1,2,5"]', "|===", "|Usage |Category |Where it runs |What it does", ""]
        for c in items:
            d = command_cmd._describe(c)
            lines += [f"|`{_cell(d['usage'])}`", f"|{c.category}", f"|{_cell(', '.join(wire_surfaces(c.surfaces)))}", f"|{_cell(c.summary)}", ""]
        lines += ["|===", ""]
    lines += ["A `decision` command is for a person: it is never offered over MCP, and the editor asks you in a dialog.", ""]
    out["docs-src/chapters/reference/commands.adoc"] = "\n".join(lines)

    # kits
    lines = [h(), "[#reference-kits]", "== Kit reference", "",
             "Each kit as it installs on Debian 13 and on Ubuntu 24.04, taken from the kits' own code. Packages come from the distribution; "
             "downloads are checked against the fingerprint in the code before anything is unpacked.", ""]
    for name, cls in sorted(r.kits.items()):
        k = cls()
        lines += [f"=== {name}", "", k.plain[0].upper() + k.plain[1:], ""]
        for label, d in (("Debian 13", DEBIAN), ("Ubuntu 24.04", UBUNTU)):
            pk = ", ".join(f"`{p}`" for p in k.apt(d)) or "none"
            lines += [f"*Packages on {label}:* {pk}", ""]
            dl = k.downloads(d)
            if dl:
                lines += [f"*Downloads on {label}:*", ""]
                lines += [f"* `{x.name}` {x.version}, for {', '.join(sorted(x.sha256))}" for x in dl] + [""]
        lines += ["*Checks:*", ""] + [f"* {c.name}" + (f" (`{c.program}`)" if c.program else "") for c in k.checks(DEBIAN)] + [""]
    out["docs-src/chapters/reference/kits.adoc"] = "\n".join(lines)

    # files
    lines = [h(), "[#reference-files]", "== Files and settings", "",
             "Where `ws-host` keeps things, following the XDG conventions, and what your configuration may say.", "",
             '[cols="2,4"]', "|===", "|Place |What is there", "",
             "|`~/.config/workspaces-host/ws-host.env`", "|your configuration", "",
             "|`~/.config/workspaces-host/secrets.env`", "|secrets, refused unless only you can read it (mode 600); `gh` and `glab` keep theirs in their own storage", "",
             "|`~/.local/share/workspaces-host/tools/<name>/<version>`", "|downloaded tools, with a `current` link to the installed version", "",
             "|`~/.local/share/workspaces-host/enabled/<repo>`", "|one link per repository you trust: the record of trust", "",
             "|`~/.local/state/workspaces-host/`", "|logs of what changed, and the commit each trust was given at", "",
             "|`~/.cache/workspaces-host/`", "|downloads, kept by fingerprint", "",
             "|`~/.local/bin/ws-host`", "|a link to the launcher in the workspaces-host clone", "",
             "|`~/workspaces/<host>/<org>/<repo>`", "|every repository", "",
             "|`<repo>/.workspaces-host/ws-host.env`", "|what a repository needs: its kit and the repositories it is worked beside", "",
             "|===", "", "=== Your configuration", "", '[cols="2,5"]', "|===", "|Key |Meaning", ""]
    lines += [f"|`{k}`|{_cell(v)}" for k, v in config.KEYS.items()]
    lines += ["|===", "", "=== A repository's file", "", '[cols="2,5"]', "|===", "|Key |Meaning", ""]
    lines += [f"|`{k}`|{_cell(v)}" for k, v in config.REPO_KEYS.items()]
    lines += ["|===", "", "A file is `KEY=value` lines, the value optionally in quotes, `#` for a comment, a list on one line separated by spaces. "
              "Nothing is expanded and a line does not continue.", ""]
    out["docs-src/chapters/reference/files.adoc"] = "\n".join(lines)

    # VS Code setup (0006-onboarding FR-008)
    from . import vscode as vs
    lines = [h(), "[#reference-vscode]", "== VS Code setup", "",
             f"What `{NAME} vscode ensure` puts in place, taken from the code. It adds a setting only when you have not set it, and it never changes one you have.", "",
             "=== Recommended extensions", "", '[cols="2,5"]', "|===", "|Extension |What it is for", ""]
    lines += [f"|`{i}`|{_cell(w)}" for i, w in vs.RECOMMENDED]
    lines += ["|===", "", "The Workspace extension itself is installed from your copy of `ws-host`, not from the Marketplace.", "",
              "=== Settings", "", '[cols="3,3"]', "|===", "|Setting |Value", ""]
    import json as _json
    lines += [f"|`{k}`|`{_cell(_json.dumps(v))}`" for k, v in sorted(vs.baseline_settings().items()) if k != "terminal.integrated.defaultProfile.linux"]
    lines += ["|`terminal.integrated.defaultProfile.linux`|`fish` when it is installed, otherwise `bash`", "|===", "",
              "Under WSL they go in `~/.vscode-server/data/Machine/settings.json`; elsewhere in your own user settings file.", ""]
    out["docs-src/chapters/reference/vscode-setup.adoc"] = "\n".join(lines)

    # topics
    lines = [h(), "[#reference-help]", "== Help topics", "",
             f"The daily work is explained by `{NAME} help`, and this chapter is the same text, taken from the same code, so that it cannot drift. "
             f"In VS Code the Learn command shows these pages with a button for each step.", ""]
    for t in sorted(r.topics.values(), key=lambda t: t.name):
        lines += [f"=== {t.name}", "", f"_{t.summary}_", "", t.plain, ""]
        for heading, text in t.sections:
            lines += [f".{heading}", _block(text), ""]
        if t.steps:
            lines += [".Steps", ""]
            for s in t.steps:
                cl = command_line(Action(s.words, s.label, dict(s.fields)), r)
                lines.append(f"* {s.label}: `{cl}`" + (f" ({s.note})" if s.note else ""))
            lines.append("")
    out["docs-src/chapters/reference/help-topics.adoc"] = "\n".join(lines)
    return out


def _block(text: str) -> str:
    """Indented lines in a topic are commands: they become listing blocks."""
    out, code = [], []
    for ln in text.split("\n"):
        if ln.startswith("    "):
            code.append(ln[4:])
            continue
        if code:
            out += ["----", *code, "----"]
            code = []
        out.append(ln)
    if code:
        out += ["----", *code, "----"]
    return "\n".join(out)


@generator("agent-skill", "skill generate", "the skill that tells an AI agent how to use ws-host")
def agent_skill() -> dict:
    r = reg.discover()
    lines = ["---", "name: ws-host",
             "description: Use ws-host, the environment orchestrator, to prepare this machine, copy and update repositories, install kits, check health, and learn the daily work. Run it as ws-host.",
             "---", "", header("md", "agent-skill", "skill generate").rstrip(), "",
             f"# {NAME}", "", f"`{NAME}` {VERSION} prepares a Debian-family machine and runs on it. Every command returns the same shape of resource; "
             "ask for JSON with `--json` and read `data.plain` first. It calls no AI model, never commits or pushes, and never changes your login shell.", "",
             "## Rules for an agent", "",
             "- A command in the `decision` category is for a person. It is not offered to you; it needs a prompt in a terminal or the editor's dialog. Tell the person what you want decided.",
             "- A command that needs `sudo` (`kit add`) is not offered to you either.",
             "- Add `--dry-run` to anything that writes, and read what it would do first.",
             "- A repository `repo sync` leaves alone is safe and is not an error; its resource says why.",
             f"- `{NAME} help` is the daily-work documentation; `{NAME} help TOPIC` for one. `{NAME} context` and `{NAME} doctor` give a report with no secrets.", "",
             "## Commands", "", "| Command | Category | Where | What it does |", "| --- | --- | --- | --- |"]
    for c in sorted(r.commands.values(), key=lambda c: c.id):
        lines.append(f"| `{c.id}` | {c.category} | {', '.join(wire_surfaces(c.surfaces))} | {c.summary} |")
    lines += ["", "## Kits", ""] + [f"- `{n}`: {cls().summary}" for n, cls in sorted(r.kits.items())]
    lines += ["", "## Help topics", ""] + [f"- `{t.name}`: {t.summary}" for t in sorted(r.topics.values(), key=lambda t: t.name)]
    lines += ["", "## Checks", "", "`doctor`, `check`, `test` and `fresh` say whether a change is sound. `docs generate` and `skill generate` rewrite generated files.",
              "", "## Extending", "",
              "Add a Python module to `ws_host/commands/`, `ws_host/kits/` or `ws_host/help/`; nothing else lists it. Import only the standard library at module level; "
              "a package goes in a dependency group of `pyproject.toml` and `uv.lock` and is imported inside the function that uses it. `ws-host help extend` has the rest.", ""]
    return {".claude/skills/ws-host/SKILL.md": "\n".join(lines)}


def _write(name: str, dry: bool) -> list[dict]:
    root = paths.repo_root()
    rows = []
    for rel, text in reg.discover().generators[name].render().items():
        f = root / rel
        old = f.read_text(encoding="utf-8") if f.exists() else None
        rows.append({"name": rel, "status": "unchanged" if old == text else ("would write" if dry else "written"), "was": "missing" if old is None else "present"})
        if not dry and old != text:
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(text, encoding="utf-8")
    return rows


@command("docs", "generate", category="generate", summary="Rewrite the guide's generated reference chapters")
def docs_generate(ctx):
    rows = _write("reference-docs", ctx.dry_run)
    n = sum(r["status"] in ("written", "would write") for r in rows)
    return Resource("docs", "generate", {"plain": "Nothing was changed. This is what I would rewrite." if ctx.dry_run else
                                                   f"The reference chapters are up to date ({n} rewritten).", "files": rows},
                    actions=[Action(("fresh",), "Prove the generated files are current")])


@command("skill", "generate", category="generate", summary="Rewrite the skill that tells an AI agent how to use ws-host")
def skill_generate(ctx):
    rows = _write("agent-skill", ctx.dry_run)
    n = sum(r["status"] in ("written", "would write") for r in rows)
    return Resource("skill", "generate", {"plain": "Nothing was changed. This is what I would rewrite." if ctx.dry_run else f"The agent skill is up to date ({n} rewritten).", "files": rows})


def stale() -> list[dict]:
    """Each generator's files compared with what its code writes now (0041 FR-036)."""
    root = paths.repo_root()
    out = []
    for name, g in sorted(reg.discover().generators.items()):
        files = []
        for rel, text in g.render().items():
            f = root / rel
            have = f.read_text(encoding="utf-8") if f.exists() else None
            files.append({"name": rel, "status": "current" if have == text else ("missing" if have is None else "stale")})
        bad = [f for f in files if f["status"] != "current"]
        out.append({"name": name, "status": "fail" if bad else "ok", "command": g.command, "files": files,
                    "plain": f"{name}: " + (f"{len(bad)} file(s) out of date; run {NAME} {g.command}" if bad else f"{len(files)} file(s) current")})
    return out


@command("fresh", category="check", summary="Prove the generated files are current",
         args=(Arg("generators", "STRING", positional=True, multiple=True),))
def fresh(ctx, generators):
    rows = [r for r in stale() if not generators or r["name"] in generators]
    if generators and len(rows) != len(set(generators)):
        raise WsError("usage", "no such generator", f"I do not know a generator called one of those. They are: {', '.join(sorted(reg.discover().generators))}.", exit_code=2)
    bad = [r for r in rows if r["status"] == "fail"]
    return Resource("fresh", "generators", {"plain": "Every generated file is current." if not bad else
                                            f"{len(bad)} generated file set{'s' if len(bad) != 1 else ''} out of date; the commands below rewrite them.",
                                            "generators": rows},
                    actions=[Action(tuple(b["command"].split()), f"Rewrite {b['name']}") for b in bad], status=FAILED if bad else OK)


@section("fresh", suites=("quick",), summary="generated files are current")
def fresh_section(ctx):
    return [{"level": "error", "where": f["name"], "message": f"is {f['status']}; rewrite it with `{NAME} {r['command']}`",
             "next": f"run `{NAME} {r['command']}`"} for r in stale() for f in r["files"] if f["status"] != "current"]


EDITIONS = ("single-page HTML", "multi-page HTML", "PDF", "EPUB")


def _have(program: str) -> bool:
    return shutil.which(program) is not None


def _run(argv, cwd=None):
    return subprocess.run(argv, cwd=cwd, capture_output=True, text=True, timeout=900)


@command("docs", "build", category="build", summary="Build the guide: HTML, PDF and, where the converter is here, EPUB",
         args=(Arg("output", "PATH", help="where to put it (default _site)"),), programs=("asciidoctor",))
def docs_build(ctx, output):
    root = paths.repo_root()
    out = Path(output) if output else root / "_site"
    book = out / "book"
    src, theme = root / "docs-src" / "manuscript.adoc", root / "docs-src" / "theme"
    plan = [{"name": "single-page HTML", "needs": "asciidoctor"}, {"name": "multi-page HTML", "needs": "asciidoctor"},
            {"name": "PDF", "needs": "asciidoctor-pdf"}, {"name": "EPUB", "needs": "asciidoctor-epub3"}]
    if ctx.dry_run:
        return Resource("docs", "build", {"plain": "Nothing was built. This is what I would build.", "output": str(out), "editions": plan})
    shutil.rmtree(out, ignore_errors=True)
    book.mkdir(parents=True)
    shutil.copy(theme / "html.css", book / "html.css")
    attrs = ["-a", f"revnumber={VERSION}", "-a", "stylesheet=html.css", "-a", "linkcss"]
    results = []

    def edition(name, argv, needs_ok=True, why=""):
        if not needs_ok:
            results.append({"name": name, "status": "skipped", "reason": why})
            return
        p = _run(argv, cwd=root)
        ok = p.returncode == 0
        results.append({"name": name, "status": "built" if ok else "failed", **({} if ok else {"reason": (p.stderr or p.stdout).strip()[-300:]})})

    # In the built site the pictures sit beside index.html, so HTML reads them from there; the PDF and EPUB read docs/ directly.
    edition("single-page HTML", ["asciidoctor", *attrs, "-a", "imagesdir=..", "-o", str(book / "single-page.html"), str(src)])
    shutil.copy(theme / "site.css", book / "site.css")
    try:
        pages = build_site(root, book, theme)
        results.append({"name": "multi-page HTML", "status": "built", "pages": len(pages)})
    except SiteError as e:
        results.append({"name": "multi-page HTML", "status": "failed", "reason": str(e)})
    with tempfile.TemporaryDirectory() as t:        # the PDF theme finds the logo beside itself; nothing in the repository is touched
        shutil.copytree(theme, Path(t) / "theme")
        shutil.copy(root / "docs" / "logo.png", Path(t) / "theme" / "logo.png")
        edition("PDF", ["asciidoctor-pdf", "-a", f"revnumber={VERSION}", "-a", "pdf-theme=if-press-pdf-theme.yml", "-a", f"pdf-themesdir={Path(t) / 'theme'}",
                        "-o", str(book / "workspaces-host.pdf"), str(src)], _have("asciidoctor-pdf"), "asciidoctor-pdf is not on this machine")
    edition("EPUB", ["asciidoctor-epub3", "-a", f"epub3-stylesheet={theme / 'epub.css'}", "-o", str(book / "workspaces-host.epub"), str(src)],
            _have("asciidoctor-epub3"), "the asciidoctor-epub3 converter is not on this machine")
    for f in ("index.html", "mascot.jpg", "mascot-workflows.jpg", "logo.png", "social-preview.jpg", ".nojekyll"):
        shutil.copy(root / "docs" / f, out / f)
    built = [r["name"] for r in results if r["status"] == "built"]
    failed = [r for r in results if r["status"] == "failed"]
    skipped = [r for r in results if r["status"] == "skipped"]
    plain = (f"Built {len(built)} of the {len(results)} editions: {', '.join(built)}." if built else "Nothing could be built.") \
        + (f" Left out because a converter is missing: {', '.join(r['name'] for r in skipped)}." if skipped else "")
    return Resource("docs", "build", {"plain": plain, "output": str(out), "editions": results},
                    actions=[Action(("kit", "add"), "Install the press kit", {"kit": "press"})] if skipped else [],
                    status=FAILED if failed or not built else OK)


class SiteError(Exception):
    pass


def _manuscript(root: Path) -> list[dict]:
    """The chapters in manuscript order with the part each belongs to."""
    out, part = [], ""
    for line in (root / "docs-src" / "manuscript.adoc").read_text(encoding="utf-8").splitlines():
        m = re.match(r"^= (Part [^\n]+)$", line)
        if m:
            part = m.group(1)
            continue
        m = re.match(r"^include::(chapters/[^\[]+\.adoc)\[\]", line)
        if m:
            rel = m.group(1)
            out.append({"file": rel, "slug": Path(rel).stem, "part": part or "Start here"})
    return out


def _render_chapter(root: Path, rel: str) -> str:
    p = subprocess.run(["asciidoctor", "-s", "-a", "imagesdir=..", "-a", "sectnums!", "-a", "icons!", "-o", "-", str(root / "docs-src" / rel)],
                       capture_output=True, text=True, timeout=300)
    if p.returncode != 0:
        raise SiteError(f"asciidoctor could not convert {rel}: {(p.stderr or '').strip()[-200:]}")
    return p.stdout


def build_site(root: Path, book: Path, theme: Path) -> list[str]:
    """One HTML page per chapter, each with the navigation beside it (0006-onboarding FR-011). Uses only asciidoctor."""
    chapters = _manuscript(root)
    if not chapters:
        raise SiteError("the manuscript includes no chapters")
    bodies, ids, titles = {}, {}, {}
    for ch in chapters:
        html_ = _render_chapter(root, ch["file"])
        bodies[ch["slug"]] = html_
        m = re.search(r"<h[12][^>]*>(.*?)</h[12]>", html_, re.S)
        titles[ch["slug"]] = re.sub(r"<[^>]+>", "", m.group(1)).strip() if m else ch["slug"].replace("-", " ").capitalize()
        for i in re.findall(r'\bid="([^"]+)"', html_):
            ids.setdefault(i, ch["slug"])
        for i, t in re.findall(r'<h[2-6] id="([^"]+)">(.*?)</h[2-6]>', html_, re.S):
            titles.setdefault("#" + i, re.sub(r"<[^>]+>", "", t).strip())
    names = []
    for n, ch in enumerate(chapters):
        slug = ch["slug"]
        body = bodies[slug]

        def fix(m):
            target, text = m.group(1), m.group(2)
            page = ids.get(target)
            href = f"#{target}" if page in (None, slug) else f"{page}.html#{target}"
            label = titles.get("#" + target, text.strip("[]")) if text.startswith("[") and text.endswith("]") else text
            return f'<a href="{href}">{label}</a>'
        body = re.sub(r'<a href="#([^"]+)">([^<]*)</a>', fix, body)
        nav, last = [], None
        for c in chapters:
            if c["part"] != last:
                nav.append(f'<div class="part">{html.escape(c["part"])}</div>')
                last = c["part"]
            cur = ' class="current"' if c["slug"] == slug else ""
            nav.append(f'<ul><li><a href="{c["slug"]}.html"{cur}>{html.escape(titles[c["slug"]])}</a></li></ul>')
        prev = f'<a href="{chapters[n - 1]["slug"]}.html">&larr; {html.escape(titles[chapters[n - 1]["slug"]])}</a>' if n else "<span></span>"
        nxt = f'<a href="{chapters[n + 1]["slug"]}.html">{html.escape(titles[chapters[n + 1]["slug"]])} &rarr;</a>' if n + 1 < len(chapters) else "<span></span>"
        page = (f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">'
                f'<title>{html.escape(titles[slug])} - Workspaces Host</title><link rel="stylesheet" href="html.css"><link rel="stylesheet" href="site.css"></head>'
                f'<body class="site"><nav class="site-nav"><a class="brand" href="../index.html"><img src="../logo.png" alt="">Workspaces Host</a>'
                f'<details open><summary>Contents</summary>{"".join(nav)}</details></nav>'
                f'<main class="site-main"><div id="content">{body}</div><div class="pager">{prev}{nxt}</div>'
                f'<footer>Workspaces Host {VERSION}. The reference is generated from the code.</footer></main></body></html>')
        (book / f"{slug}.html").write_text(page, encoding="utf-8")
        names.append(slug)
    shutil.copy(book / f"{chapters[0]['slug']}.html", book / "index.html")
    return names
